###
POST http://localhost:3000/auth/forget-password
Content-Type: application/json

{
    "email": "janyeongsil@gmail.com"
}

###
POST http://localhost:3000/auth/verify-otp
Content-Type: application/json

{
    "email": "janyeongsil@gmail.com",
    "otp": "501084",
    "newPassword": "12345"
}